### ISSUE TITLE
Add Adapter interfaces for payment gateways libraries

### ISSUE THREAD

**Issue by marcoalbarelli** [leaphly/cart#1]
In order to have a decoupled cart library, that's still useful enough to actually build a e-commerce it would be helpful to have adapter interfaces to adapt the ItemInterface (and all other needed intarfaces) to various Payment libraries like for instance Omnipay

To integrate with OmniPay a single adapter should suffice: from ItemInterface to ItemInterface
https://github.com/omnipay/common/blob/master/src/Omnipay/Common/ItemInterface.php

I already forked leaphly/cart and I'm going to try writing something in the next few days

**Comment by liuggio** [comment]
Great Idea!!
Maybe I don't get how, you mean could be great have a service that could convert from one item to another?
what `single adapter` means for you?
waiting your concept :)

**Comment by marcoalbarelli** [comment]
I mean to use the [adapter pattern](http://en.wikipedia.org/wiki/Adapter_pattern) 
The best approach (imho) would be to have a factory service of some kind that uses a configuration enabled adapter, performing all needed adaptation at runtime before feeding the Payment Library, but of course this would need some thought, since the payment gateway may need to serialize the _Order_ in some way

It would be quite a tricky task to allow good integration keeping everything well decoupled

My guess is that the adapter layer will end up to be quite thick and of course most of it will be very specific for the Payment Library
